<?php
namespace AppBundle\Form;

use AppBundle\Form\EventListener\EventsSearchListener;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Class EventsSearchForm
 * @package AppBundle\Form
 */
class EventsSearchType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $date = new \DateTimeImmutable('now', new \DateTimeZone('America/New_York'));
        $week = $date->add(new \DateInterval('P7D'));
        $month = $date->add(new \DateInterval('P1M'));

        $builder
            ->add('category', ChoiceType::class, [
                'label' => 'Show me',
                'choices' => [
                    'Everything' => 'all',
                    'Author Talks & Gatherings' => '8171',
                    'Career & Finance' => '8177',
                    'Children & Family' => '8174',
                    'Computers & Workshops' => '8175',
                    'Exhibitions' => '8172',
                    'Health & Fitness' => '8176',
                    'Performing Arts & Films' => '8173',
                    'Tours' => '8178',
                ]
            ])
            ->add('location', ChoiceType::class, [
                'label' => 'in',
                'choices' => [
                    'Everywhere' => 'all',
                    'The Bronx' => 'Bronx',
                    'Manhattan' => 'Manhattan',
                    'Staten Island' => 'Staten+Island',
                ]
            ])
            ->add('audience', ChoiceType::class, [
                'label' => 'for',
                'choices' => [
                    'Everyone' => 'all',
                    'Adults' => 'Adult',
                    'Teens/Young Adults' => 'Young Adult',
                    'Kids & Families' => 'Children',
                ]
            ])
            ->add('date', ChoiceType::class, [
                'label' => 'happening',
                'choices' => [
                    'Anytime' => 'all',
                    'Today' => '[' . $date->format('Y-m-d') .'T00:00:00Z TO ' . $date->format('Y-m-d') .'T23:59:59Z]',
                    'This Week' => '[' . $date->format('Y-m-d') .'T00:00:00Z TO '. $week->format('Y-m-d') .'T23:59:59Z]',
                    'This Month' => '[' . $date->format('Y-m-d') .'T00:00:00Z TO '. $month->format('Y-m-d') .'T23:59:59Z]',
                ],
            ])
            ->add('submit', SubmitType::class, ['label' => 'Search'])
            ->addEventListener(FormEvents::POST_SUBMIT, [$this, 'onPostSubmit'])
        ;

        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
    }

    public function onPostSubmit(FormEvent $event)
    {
        $category = $event->getForm()->getData();
        $event->setData($category);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'AppBundle\Entity\EventsSearch',
        ));
    }
}
